# -*- mode: ruby -*-
# vi: set ft=ruby :

# Sobe um servidor apache2 basico usando um alpine como base

Vagrant.configure("2") do |config|
  config.vm.define "alpine" do |alpine|
    alpine.vm.box = "generic/alpine318"
    config.vm.network "private_network", ip: "192.168.56.10"  
    # config.vm.network "public_network"

    alpine.vm.provision "shell", inline: <<-SHELL
      sudo apk update
      sudo apk add apache2
      sudo service apache2 start
    SHELL
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end
end
