# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "debian" do |deb12|
    deb12.vm.box = "generic/debian12"
    deb12.vm.hostname = "debian12"
    deb12.vm.network "public_network"

    deb12.vm.provision "shell", inline: <<-SHELL
      echo "alias cls='clear'" >> .bashrc
      source .bashrc
      apt update -y
      apt install xfce4-session xfce4-goodies xinit -y
    SHELL
  end

    config.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 1
    end
  end
end
