# -*- mode: ruby -*-
# vi: set ft=ruby :

# Apenas uma maquina basica com centos

Vagrant.configure("2") do |config|
  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/7"
    centos.vm.network "public_network",
      use_dhcp_assigned_default_route: true

    centos.vm.provision "shell", inline: <<-SHELL
      sudo yum update -y
    SHELL
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end
end