# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "debian" do |debian|
    debian.vm.hostname = "nsd"
    debian.vm.box = "generic/debian12"

    debian.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install nsd
    SHELL

    config.vm.provider "virtualbox" do |v|
      v.name = "nsd"
      v.memory = 512
      v.cpus = 1
    end
  end
end
