# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
config.vm.network "public_network", bridge: "enp3s0"

  # Recursive
  for i in 1..2 do
    config.vm.define "dns-recursive-#{i}" do |rec|
      rec.vm.box = "ubuntu/focal64"

      rec.vm.provision "shell", inline: <<-SHELL
        sudo apt update
        sudo apt install unbound -y
      SHELL
    end
  end

  # Autoritative
  for i in 1..2 do
    config.vm.define "dns-autoritative-#{i}" do |aut|
      aut.vm.box = "ubuntu/focal64"
    
      aut.vm.provision "shell", inline: <<-SHELL
        sudo apt update
        sudo apt install nsd -y
      SHELL
    end
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end
end