# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "ftp" do |ftp|
    ftp.vm.hostname = "ftp"
    ftp.vm.box = "ubuntu/focal64"

    ftp.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install -y vsftpd
    SHELL

    config.vm.provider "virtualbox" do |v|
      v.name = "ftp"
      v.memory = 512
      v.cpus = 1
    end
  end
end
