# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "debian" do |debian|
  config.vm.hostname = "pihole"
    debian.vm.box = "generic/debian10"
      debian.vm.network "public_network"

    debian.vm.provision "shell", inline: <<-SHELL
      echo "alias cls='clear'" >> .bashrc
      apt update -y
      apt install unbound -y 
      wget -O basic-install.sh https://install.pi-hole.net
    SHELL
  end

  config.vm.provider "virtualbox" do |v|
    v.name = "pi-hole"
    v.memory = 512
    v.cpus = 1
  end
end
