# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "apache" do |apache|
    apache.vm.hostname = "apache"
    apache.vm.box = "ubuntu/focal64"

    apache.vm.provision "shell", inline: <<-SHELL
      apt update ; apt upgrade -y
      apt install -y apache2
    SHELL

    config.vm.provider "virtualbox" do |v|
      v.name = "apache"
      v.memory = 512
      v.cpus = 1
    end
  end
end
