# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "webmin" do |webmin|
    webmin.vm.hostname = "webmin"
    webmin.vm.box = "ubuntu/jammy64"
    webmin.vm.network "public_network", bridge: [
      'Intel(R) Ethernet Connection (17) I219-LM',
      'Hyper-V Virtual Ethernet Adapter',
    ]

    webmin.vm.provision "shell", inline: <<-SHELL
      # Evita prompts interativos
      export DEBIAN_FRONTEND=noninteractive

      apt update

      # Instala pacotes essenciais
      apt install -y git vim make python3-full net-tools

      # Baixa e instala Webmin corretamente
      curl -o webmin-setup-repo.sh https://raw.githubusercontent.com/webmin/webmin/master/webmin-setup-repo.sh
      chmod +x webmin-setup-repo.sh
      ./webmin-setup-repo.sh -f
      apt install -y webmin usermin --install-recommends

      # Se quiser atualizar a distro sem perguntas, descomente:
      # do-release-upgrade -f DistUpgradeViewNonInteractive -q
    SHELL

    config.vm.provider "virtualbox" do |v|
      v.cpus = 4
      v.memory = 4096
    end
  end
end
