# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "debian" do |debian|
  config.vm.hostname = "pihole2"
    debian.vm.box = "generic/debian12"
    debian.vm.network "private_network", ip: "10.1.1.100"

    debian.vm.provision "shell", inline: <<-SHELL
      echo "alias ll='ls -lhF'" >> .bashrc
      echo "alias cls='clear'" >> .bashrc
      source .bashrc
      apt update -y
      apt install unbound -y 
      wget -O basic-install.sh https://install.pi-hole.net
    SHELL
  end

  config.vm.provider "virtualbox" do |v|
    v.name = "pihole with devian12"
    v.memory = 512
    v.cpus = 1
  end
end
