# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubnt|
    ubnt.vm.box = "ubuntu/focal64"

    ubnt.vm.provision "shell", inline: <<-SHELL
      sudo apt update -y
      sudo apt upgrade -y
    SHELL

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end
end
