# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/focal64"
      ubuntu.vm.network "public_network"

    ubuntu.vm.provision "shell", inline: <<-SHELL
      sudo echo "alias cls='clear'" >> .bashrc
      sudo apt update -y
      sudo apt install xfce4-session xfce4-goodies xinit -y
    SHELL
  end

  # config.vm.provider "virtualbox" do |v|
  #   v.memory = 512
  #   v.cpus = 1
  # end
end