
# -*- mode: ruby -*-
# vi: set ft=ruby :

# cockpanel = cockpit + 1panel

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |cockpanel|
    cockpanel.vm.hostname = "cockpanel"
    cockpanel.vm.box = "ubuntu/focal64"
    cockpanel.vm.network "public_network"


    cockpanel.vm.provision "shell", inline: <<-SHELL
      # Evita prompts interativos
      export DEBIAN_FRONTEND=noninteractive

      # Atualiza e limpa pacotes
      apt update && apt full-upgrade -y && apt autoremove -y && apt autoclean -y

      # Instala pacotes essenciais
      apt install -y git vim make python3-full net-tools cockpit

      # Baixa e instala Webmin corretamente
      curl -sSL https://resource.1panel.pro/quick_start.sh -o quick_start.sh
      chmod +x quick_start.sh
      ./quick_start.sh -f
      
      # Se quiser atualizar a distro sem perguntas, descomente:
      # do-release-upgrade -f DistUpgradeViewNonInteractive -q
    SHELL


    config.vm.provider "virtualbox" do |v|
      v.name = "cockpanel"
      v.memory = 2024
      v.cpus = 2
    end
  end
end
