# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/focal64"
    ubuntu.vm.hostname = "proftpd"
      ubuntu.vm.network "public_network"

    ubuntu.vm.provision "shell", inline: <<-SHELL
      echo "alias cls='clear'" >> .bashrc && source .bashrc
      apt update -y
      sudo apt-get install proftpd -y
      hostname -I
      cp /vagrant/id_rsa.pub /home/vagrant/
      cat id_rsa.pub >> .ssh/authorized_keys
    SHELL
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end
end
