# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
config.vm.box = "ubuntu/jammy64"
config.vm.network "public_network", bridge: [
  "Intel(R) Ethernet Connection (17) I219-LM",
  "Hyper-V Virtual Ethernet Adapter",
]

config.vm.provision "shell", inline: <<-SHELL
  apt update
  apt install cockpit ansible -y
SHELL

config.vm.provider "virtualbox" do |v|
  v.memory = 512
  v.cpus = 1
end

  # client
  (1..3).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.hostname = "node#{i}"
      node.vm.provider "virtualbox" do |v|
        v.name = "node#{i}"
      end
    end
  end
end